changed pattern for tags to publish to testpypi to align with there release candidate naming sheme

diff --git a/.woodpecker.yml b/.woodpecker.yml
--- a/.woodpecker.yml
+++ b/.woodpecker.yml
@@ -74,14 +74,14 @@ steps:
     commands:
       - VERSION="${CI_COMMIT_TAG#v}"
       - |
-        if echo "$CI_COMMIT_TAG" | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+$'; then
+        if echo "$CI_COMMIT_TAG" | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+rc[0-9]+$'; then
           INDEX_URL="https://test.pypi.org/pypi/pazufa-corelib/$VERSION/json"
           INDEX_NAME="TestPyPI"
         elif echo "$CI_COMMIT_TAG" | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+$'; then
           INDEX_URL="https://pypi.org/pypi/pazufa-corelib/$VERSION/json"
           INDEX_NAME="PyPI"
         else
-          echo "ERROR: tag '$CI_COMMIT_TAG' does not match a recognized release pattern (vX.Y.Z or vX.Y.Z-rcN)" >&2
+          echo "ERROR: tag '$CI_COMMIT_TAG' does not match a recognized release pattern (vX.Y.Z or vX.Y.ZrcN)" >&2
           exit 1
         fi
         export INDEX_URL INDEX_NAME VERSION
@@ -124,7 +124,7 @@ steps:
     image: python:3.12-slim
     depends_on: [check-dist]
     when:
-      - evaluate: 'CI_COMMIT_TAG matches "^v[0-9]+[.][0-9]+[.][0-9]+-rc[0-9]+$"'
+      - evaluate: 'CI_COMMIT_TAG matches "^v[0-9]+[.][0-9]+[.][0-9]+rc[0-9]+$"'
     environment:
       TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
       TWINE_USERNAME: __token__
